services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13306:3306"
      #    volumes:
      # 设置初始化脚本
    #      - ./script/mysql/:/docker-entrypoint-initdb.d/
  redis:
    image: redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "16379:6379"
